# This workflow runs full unit tests on a matrix of OS and NodeJS combinations.

name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the specified branches
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'Validate build'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 16
          - 18
          - 20
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'
    name: 'Node ${{ matrix.node }} (${{ matrix.os }})'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
